FrontEndApp/FrontEndApp/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using FrontEndApp.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Authorization;

namespace FrontEndApp.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        HttpMessageHandler _handler;
        private string cartServiceLink;

        public CartController(IConfiguration config, HttpMessageHandler handler = null)
        {
            _handler = handler == null ? new HttpClientHandler() : handler;
            cartServiceLink = config.GetValue<string>("CartService");
        }

        [Route("Cart/Index")]
        public IActionResult Index()
        {
            Client client = new Client();
            
            //Read cookie
            string cookievalue = "";
            if (Request.Cookies["access_token"] != null)
            {
                cookievalue = Request.Cookies["access_token"].ToString();
            }

            PartialVM vm = client.GetClient(cartServiceLink, "api/CustomerOrdering/View/Cart", cookievalue, "Cart Service Down", _handler);
            return View("Shared/Simple", vm);
        }

        [Route("MyOrders")]
        public IActionResult MyOrders()
        {
            Client client = new Client();

            //Read cookie
            string cookievalue = "";
            if (Request.Cookies["access_token"] != null)
            {
                cookievalue = Request.Cookies["access_token"].ToString();
            }

            PartialVM vm = client.GetClient(cartServiceLink, "api/CustomerOrdering/View/Orders", cookievalue, "Order Service Down", _handler);
            return View("Shared/Simple", vm);
        }
    }
}

FrontEndApp/FrontEndApp/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using Microsoft.Extensions.Configuration;
using FrontEndApp.Models;

namespace FrontEndApp.Controllers
{
    public class InvoiceController : Controller
    {
        HttpMessageHandler _handler;
        private string invoiceServiceLink;

        public InvoiceController(IConfiguration config, HttpMessageHandler handler = null)
        {
            _handler = handler == null ? new HttpClientHandler() : handler;
            invoiceServiceLink = config.GetValue<string>("InvoiceService");
        }

        public IActionResult InvoicesForApproval()
        {
            Client client = new Client();

            //Read cookie
            string cookievalue = "";
            if (Request.Cookies["access_token"] != null)
            {
                cookievalue = Request.Cookies["access_token"].ToString();
            }

            PartialVM vm = client.GetClient(invoiceServiceLink, "/api/Invoice/Views/InvoicesForApproval", cookievalue, "Invoice Service Down", _handler);
            return View(vm);
        }


        public IActionResult InvoicesForUser(string id)
        {
            Client client = new Client();

            //Read cookie
            string cookievalue = "";
            if (Request.Cookies["access_token"] != null)
            {
                cookievalue = Request.Cookies["access_token"].ToString();
            }

            PartialVM vm = client.GetClient(invoiceServiceLink, "/api/Invoice/Views/InvoicesForUsers/" + id, cookievalue, "Invoice Service Down", _handler);
            return View(vm);
        }


        public IActionResult InvoicesDetails(string reference)
        {
            Client client = new Client();

            //Read cookie
            string cookievalue = "";
            if (Request.Cookies["access_token"] != null)
            {
                cookievalue = Request.Cookies["access_token"].ToString();
            }

            PartialVM vm = client.GetClient(invoiceServiceLink, "/api/Invoice/Views/InvoiceDetails/" + reference, cookievalue, "Invoice Service Down", _handler);
            return View(vm);
        }
    }
}

FrontEndApp/FrontEndApp/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Authorization;
using FrontEndApp.Models;
using System.Net.Http;
using Microsoft.AspNetCore.Authentication.JwtBearer;

namespace FrontEndApp.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        HttpMessageHandler _handler;
        private string profileServiceLink;

        public ProfileController(IConfiguration config, HttpMessageHandler handler = null)
        {
            _handler = handler == null ? new HttpClientHandler() : handler;
            profileServiceLink = config.GetValue<string>("ProfileService");
        }

        // GET: Profile
        // /User/Index
        [HttpGet]
        [Route("User/Index")]
        public ActionResult Index()
        {
            Client client = new Client();

            //Read cookie
            string cookievalue = "";
            if (Request.Cookies["access_token"] != null)
            {
                cookievalue = Request.Cookies["access_token"].ToString();
            }

            PartialVM vm = client.GetClient(profileServiceLink, "/User/Index", cookievalue, "User Service Down", _handler);
            return View(vm);
        }

        // GET: User/Profile/5
        [HttpGet]
        [Route("User/Profile/{id}")]
        public ActionResult Profile(string id)
        {
            Client client = new Client();

            //Read cookie
            string cookievalue = "";
            if (Request.Cookies["access_token"] != null)
            {
                cookievalue = Request.Cookies["access_token"].ToString();
            }

            PartialVM vm = client.GetClient(profileServiceLink, "/User/Profile/" + id, cookievalue, "User Service Down", _handler);
            return View(vm);
        }

        // GET: User/Edit/5
        [HttpGet]
        [Route("User/Edit/{id}")]
        public ActionResult Edit(string id)
        {
            Client client = new Client();

            //Read cookie
            string cookievalue = "";
            if (Request.Cookies["access_token"] != null)
            {
                cookievalue = Request.Cookies["access_token"].ToString();
            }

            PartialVM vm = client.GetClient(profileServiceLink, "/User/Edit/" + id, cookievalue, "User Service Down", _handler);
            return View(vm);
        }

        [HttpPost]
        public IActionResult EditProfilePost(User model)
        {
            using (HttpClient client = new HttpClient(_handler, false))
            {
                var response = client.PostAsJsonAsync(profileServiceLink + "/User/EditProfilePost", model).Result;
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return NotFound();
                }
            }
        }
    }
}

FrontEndApp/FrontEndApp/Controllers/StaffOrderingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FrontEndApp.Models;
using System.Net.Http;
using Microsoft.Extensions.Configuration;

namespace FrontEndApp.Controllers
{
    public class StaffOrderingController : Controller
    {
        HttpMessageHandler _handler;
        private string staffOrderingServiceLink;
        private string productServiceLink;

        public StaffOrderingController(IConfiguration config, HttpMessageHandler handler = null)
        {
            _handler = handler == null ? new HttpClientHandler() : handler;
            staffOrderingServiceLink = config.GetValue<string>("StaffService");
            productServiceLink = config.GetValue<string>("ProductService");
        }

        [Route("StockOrdering/Index")]
        public IActionResult Index()
        {
            Client client = new Client();

            //Read cookie
            string cookievalue = "";
            if (Request.Cookies["access_token"] != null)
            {
                cookievalue = Request.Cookies["access_token"].ToString();
            }

            PartialVM vm = client.GetClient(staffOrderingServiceLink, "api/StaffOrdering/View/Products", cookievalue, "Stock Ordering Service Down", _handler);
            return View("Shared/Simple", vm);
        }

        [Route("StockOrdering/Cart")]
        public IActionResult Cart()
        {
            Client client = new Client();

            //Read cookie
            string cookievalue = "";
            if (Request.Cookies["access_token"] != null)
            {
                cookievalue = Request.Cookies["access_token"].ToString();
            }

            PartialVM vm = client.GetClient(staffOrderingServiceLink, "api/StaffOrdering/View/Cart", cookievalue, "Stock Ordering Service Down", _handler);
            return View("Shared/Simple", vm);
        }

        [Route("StockOrdering/LowStock")]
        public IActionResult LowStock()
        {
            Client client = new Client();

            //Read cookie
            string cookievalue = "";
            if (Request.Cookies["access_token"] != null)
            {
                cookievalue = Request.Cookies["access_token"].ToString();
            }

            PartialVM vm = client.GetClient(staffOrderingServiceLink, "api/StaffOrdering/View/LowStock", cookievalue, "Stock Ordering Service Down", _handler);
            return View("Shared/Simple", vm);
        }

        [Route("StockOrdering/Orders")]
        public IActionResult Orders()
        {
            Client client = new Client();

            //Read cookie
            string cookievalue = "";
            if (Request.Cookies["access_token"] != null)
            {
                cookievalue = Request.Cookies["access_token"].ToString();
            }

            PartialVM vm = client.GetClient(staffOrderingServiceLink, "api/StaffOrdering/View/Orders", cookievalue, "Stock Ordering Service Down", _handler);
            return View("Shared/Simple", vm);
        }

        [Route("StockOrdering/Order/{orderId}")]
        public IActionResult Order(int orderId)
        {
            Client client = new Client();

            //Read cookie
            string cookievalue = "";
            if (Request.Cookies["access_token"] != null)
            {
                cookievalue = Request.Cookies["access_token"].ToString();
            }

            PartialVM vm = client.GetClient(staffOrderingServiceLink, "api/StaffOrdering/View/Products/Order/" + orderId, cookievalue, "Stock Ordering Service Down", _handler);
            return View("Shared/Simple", vm);
        }

        [Route("StockOrdering/ProductDetails")]
        public IActionResult ProductDetails(string ean)
        {
            Client client = new Client();

            //Read cookie
            string cookievalue = "";
            if (Request.Cookies["access_token"] != null)
            {
                cookievalue = Request.Cookies["access_token"].ToString();
            }

            List<string> vms = new List<string>();

            vms.Add(client.GetClient(staffOrderingServiceLink, "api/StaffOrdering/View/ProductDetails?ean=" + ean, cookievalue, "Stock Ordering Service Down", _handler).PartialView);
            vms.Add(client.GetClient(staffOrderingServiceLink, "api/Product/Views/PriceHistory?ean=" + ean, cookievalue, "Product Service Down", _handler).PartialView);

            return View("Shared/Partials", vms);
        }
    }
}

FrontEndApp/FrontEndApp/Views/Shared/Partials.cshtml
@model List<string>

<div>
    @foreach (string s in Model)
    {
        @Html.Raw(s)
    }
</div>

FrontEndApp/FrontEndApp/Views/Shared/Simple.cshtml
@model PartialVM

<div>
    @Html.Raw(@Model.PartialView)
</div>

FrontEndApp/FrontEndApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="~/assets/ExecuteAJAX.js"></script>
<script type="text/javascript" src="~/lib/jQuery/dist/jquery.js"></script>


<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ThAmCo</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ThAmCo</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("Staff") || User.IsInRole("Admin"))
                    {
                        <li><a asp-area="" asp-controller="Profile" asp-action="Index">Users</a></li>
                        <li><a asp-area="" asp-controller="StaffOrdering" asp-action="Index">Purchase Stock</a></li>
                        <li><a asp-area="" asp-controller="StaffOrdering" asp-action="Orders">Orders</a></li>
                        <li><a asp-area="" asp-controller="StaffOrdering" asp-action="LowStock">Low Stock</a></li>
                    }
                    else if (User.IsInRole("Customer"))
                    {
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Products</a></li>
                        <li><a asp-area="" asp-controller="Cart" asp-action="MyOrders">Orders</a></li>
                        <li><a asp-area="" asp-controller="StaffOrdering" asp-action="LowStock">Low Stock</a></li>
                        <li><a asp-area="" asp-controller="Invoice" asp-action="LowStock">Low Stock</a></li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (User.IsInRole("Staff") || User.IsInRole("Admin"))
                    {
                        <li>Cart</li>
                    }
                    else if (User.IsInRole("Customer"))
                    {
                        <li>Cart</li>
                    }
                    @if (!User.IsInRole("User") && !User.IsInRole("Customer") && !User.IsInRole("Staff") && !User.IsInRole("Admin"))
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Register">Register</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Log in</a></li>
                    }
                    else
                    {
                        <li style="color: white">Welcome @User.FindFirst(System.Security.Claims.ClaimTypes.Name).Value</li>
                        <li><a asp-area="" asp-controller="Profile" asp-action="Profile" asp-route-id="@User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier).Value">Profile</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">Log Out</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - ThAmCo</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>